server:
  port: ${PORT:8080}

spring:
  application:
    name: logs-demo-service

app:
  other-service-url: ${OTHER_SERVICE_URL:}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
